### ISSUE TITLE
Please remove Derek from your organisation

### ISSUE THREAD

**Issue by alexellis** [Paperspace/gradient-installer#90]
Hi 👋 since you are not actually using, Derek please could you remove the integration from your organisation? The bot is getting a lot of unnecessary messages from your organisation. You can remove it at: https://github.com/settings/installations

Someone may have installed Derek onto your whole GitHub org.

Derek -> github.com/alexellis/derek

We are getting lots of pings from a "PS_WEB" repo.

Feel free to email me alex@openfaas.com

Alex

**Comment by alexellis** [comment]
@weikaolun @paperspace-philip

**Comment by paperspace-philip** [comment]
@alexellis it should be removed, sorry about that!
